apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
data:
  admin.password: "JDJ5JDEwJENRTGdHRWJwdXZrMm0wcDF0NUhYZ3VIZ2JKR2tmRXR6QjBUekwxdHlwSkE1REFaR3BmQ2hl"
